// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcyleuhtrrzzrwglvnlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjeWxldWh0cnJ6enJ3Z2x2bmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjQxMDEsImV4cCI6MjA2NjUwMDEwMX0.x-jNMySXqf1tbxXqv-cy6QtLa8mbgAX-K30WaxSkPuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);